name: web_directional_text_field
description: minimal web implementation for TextField and TextFormField
version: 0.0.5
homepage: https://github.com/bar4488/web_directional_text_field

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: